spring.application.name=atlas-index
server.port=8080

spring.datasource.url=${ATLASINDEX_DB}
spring.datasource.username=${ATLASINDEX_U}
spring.datasource.password=${ATLASINDEX_P}
# Optional: configure DDL auto-generation for development (use migration tools for production)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE

atlas.admin.token=${ATLAS_ADMIN}