spring.application.name=atlas-index
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/atlasIndex
spring.datasource.username=kuroneko
spring.datasource.password=
# Optional: configure DDL auto-generation for development (use migration tools for production)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE